site_name: MkDocs Slides Plugin
site_description: A plugin for MkDocs that enables beautiful slide presentations within documentation
repo_url: https://github.com/ianderrington/mkdocs_slides
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy
  markdown_extensions:
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - slides:
      font_size: "28px"
      template: "layouts/slide_template.html"

nav:
  - Home: index.md
  - Demo:
    - slides/slides_demo.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
