site_name: MkDocs Slides Plugin
site_description: A plugin for MkDocs that enables beautiful slide presentations within documentation
repo_url: https://github.com/yourusername/mkdocs-slides
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

plugins:
  - search
  - slides  # Our plugin

nav:
  - Home: index.md
  - Demo:
    - slides/slides_demo.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
